### ISSUE TITLE
BUD Algorithm Bug

### ISSUE THREAD

**Issue by glickmac** [NCBI-Hackathons/VirusCore#2]
There is a memory error with the implementation of the bud algorithm. The process of checking if a fasta file is extended is not completed due to too many files being created for individual contigs to check against the contigs_extend perl script. Either moving the fasta data into a dictionary or reading each contig by line is necessary to avoid creating the large amount of files for both the input and output.

**Comment by pcantalupo** [comment]
Please post the exact error message. Do you have a small test set of input sequences that can reproduce the error?

**Comment by glickmac** [comment]
./budding.sh: line 66: /usr/local/bin/rename: Argument list too long

The error seems to stem from the process of splitting each contig into a unique file. I will post the test set I am using onto the Slack with the necessary files (Contig file needed + perl scripts) Caution: this may take an hour to assembly even after ends are the input.

**Comment by pcantalupo** [comment]
You could fix this with xargs https://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands#11289567

But why do you need the rename? Probably because of [line 69 (the for loop)](https://github.com/NCBI-Hackathons/ViruSpy/blob/e89eb9a4953869e4cb41499d2bb04af51bf60988/scripts/budding.sh#L69) because it doesn't work with files names with spaces. You can fix this by setting the `IFS` variable appropriately. https://www.cyberciti.biz/tips/handling-filenames-with-spaces-in-bash.html

**Comment by glickmac** [comment]
I think you identified the problem! I am going to try to put the rename command into a for loop. If that doesn't work then I will try removing the rename and operating with the IFS variable.

**Comment by DCGenomics** [comment]
You people are my heroes

**Comment by glickmac** [comment]
The loop removes the bug! Woot!
